### ISSUE TITLE
When there are 2 counts with 1 zero, the piechart does not show up

### ISSUE THREAD

**Issue by TimvdLippe** [timeu/svg-piechart#4]
We have a list of `[7, 0]` which causes the pie-chart to not show up. The expected behaviour is to show the pie-chart full of 1 color (the one of the 7).

**Comment by timeu** [comment]
thanks for the bug report. I will look into it.

**Comment by JeremybellEU** [comment]
Confirmed fixed. Thanks for the very speedy response and fix!
